version: '3.9'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # ホストのポート3000で公開
    volumes:
      - .:/app  # ソースコードの同期
    command: npm run start  # React 開発サーバーを起動

  db:
    image: mysql:8.0
    container_name: hackathon-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hackathon
      MYSQL_USER: hackathon_user
      MYSQL_PASSWORD: hackathon_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
